task_list:
    path:     /tasks
    defaults: { _controller: TaskBundle:Default:index }
    
task_create:
    path:     /task/create
    defaults: { _controller: TaskBundle:Default:taskCreate }
    
task_delete:
    path:     /task/delete/{id}
    defaults: { _controller: TaskBundle:Default:taskDelete }
    requirements:
        id: \d+
        
task_update:
    path:     /task/update/{id}
    defaults: { _controller: TaskBundle:Default:taskUpdate }
    requirements:
        id: \d+